spring:
  application:
    name: team-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nba_stats
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: team
  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: team
    default-schema: team
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8087